#!/bin/sh

if timeout 1 ping -c 1 1.1.1.1 >/dev/null 2>&1; then
	echo Ping to 1.1.1.1 succeeded.
else
	echo Ping to 1.1.1.1 failed.
	exit 1
fi

if timeout 1 nslookup google.com >/dev/null 2>&1; then
	echo NSLookup succeeded.
else
	echo NSLookup failed.
	exit 1
fi

echo "All OK"
