#!/bin/sh

set -eu

# find out what directory are we running from if it's not already set
if [ -z "${ROOT-}" ]; then
	cd "$(dirname "$0")"/../..
	ROOT="$PWD"
fi

# name for logging purposes
NAME="sleep"

# we don't use it
#PID_FILE="$ROOT/var/run/$name.pid"

# process to monitor
PEXP="/bin/sh $ROOT/bin/sleepd -D"

DAEMON="$ROOT/bin/sleepd"

. "$ROOT/etc/rc.subr"

rc_run "$1"
