#!/bin/sh

set -eu

HERE="$(
	cd "$(dirname "$0")"
	pwd
)"

ROOT="${ROOT:-$HERE/../..}"

SLEEP_PID_FILE="$ROOT/var/run/profileinit/sleep.pid"

sleep_start(){
	sleep 99999 &
	echo "$!" > "$SLEEP_PID_FILE"
}

case "$1" in
	start)
		echo "Starting sleep daemon"
		if [ -s "$SLEEP_PID_FILE" ]; then
			echo "apparently already running"
		else
			sleep_start
		fi
		;;
	stop)
		echo "Stopping sleep daemon"

		if [ -s "$SLEEP_PID_FILE" ]; then
			kill -15 "$(cat "$SLEEP_PID_FILE")" || true
			rm -f "$SLEEP_PID_FILE"
		fi
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	status)
		if [ -s "$SLEEP_PID_FILE" ] && kill -0 "$(cat "$SLEEP_PID_FILE" 2>&1)" >/dev/null 2>&1; then
			echo sleep is running
		else
			echo sleep is not running
			exit 1
		fi
		;;
	*)
		echo "Usage: /etc/init.d/rsync {start|stop|restart|status}"
		exit 1
		;;
esac
	
