#!/bin/sh
set -eu

service_dir="$ROOT/etc/rc.d"

. "$ROOT/etc/rc.conf"

find "$service_dir" -type f | sort | while read -r service; do
	service_short="$(basename "$service")"

	case "$(eval 'echo $'"$service_short")" in
	YES) "$service" start ;;
	esac
done

if [ -f "$ROOT/etc/rc.local" ]; then
	"$ROOT/etc/rc.local"
fi

exit 0
