#!/bin/sh
set -eu

service_dir="$ROOT/etc/rc.d"

. "$ROOT/etc/rc.conf"
. "$ROOT/etc/rc.subr"

services="$(find "$service_dir" -type f | sort)"

for service in $services; do
	service_short="$(basename "$service")"

	eval "do=\$${service_short}"

	case "$do" in
	YES)
		set -- start
		. "$service"
		;;
	esac
done

if [ -f "$ROOT/etc/rc.local" ]; then
	. "$ROOT/etc/rc.local"
fi
