#!/bin/sh

set -eu

if [ -z "${ROOT-}" ]; then
	cd "$(dirname "$0")/.."
	ROOT="$PWD"
fi

service_dir="$ROOT/etc/rc.d"

. "$ROOT/etc/rc.subr"
. "$ROOT/etc/rc.conf"

log_file="$ROOT/var/log/userinit/messages"

services="$(awk -F'=' '/^#/ { next } { print $1 }' "$ROOT/etc/rc.conf")"

for service in $services; do
	service_short="$(basename "$service")"

	eval "do=\${${service_short}-}"

	case "$do" in
	YES)
		set -- start
		. "$service_dir/$service"
		;;
	esac
done

if [ -f "$ROOT/etc/rc.local" ]; then
	. "$ROOT/etc/rc.local"
fi

log "init complete"
